#ifndef SURVEYOR_BRANCHED_QUEUE_H
#define SURVEYOR_BRANCHED_QUEUE_H

/*
 This templated version of a Branched Queue was generated from the original versions specialized
  for EdgeType = Edge_t, ElementType = Read_pt, ElementSetStype = ReadSet_t, ContextType = AlignmentMap_t
  Defined in "edge_utils.h"
  The templated version was generated by Google Gemini Flash 3.5 after being provided the specialized code and the types
*/

#include <forward_list>
#include <memory>
#include <stdexcept>

// Forward declarations
template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
class BranchedQueueNode_t;

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
class CBranchedQueue;

// Type Aliases for readability
template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
using BranchedQueueNode_pt = std::unique_ptr<BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>>;

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
using BranchedQueueNodeList_t = std::forward_list<BranchedQueueNode_pt<EdgeType, ElementType, ElementSetType, ContextType>>;

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
using CBranchedQueue_pt = std::unique_ptr<CBranchedQueue<EdgeType, ElementType, ElementSetType, ContextType>>;


//### The Node Template
template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
struct BranchedQueueNode_t {
public:
    friend class CBranchedQueue<EdgeType, ElementType, ElementSetType, ContextType>;

protected:
    CBranchedQueue_pt<EdgeType, ElementType, ElementSetType, ContextType> childQueue;
    ElementSetType descendentElements;
    EdgeType edge;
    ElementSetType originalElements;

public:
    BranchedQueueNode_t(const EdgeType& e)
        : childQueue(nullptr), descendentElements(e.readSet), edge(e), originalElements(e.readSet) {}

protected:
    void addNode(BranchedQueueNode_pt<EdgeType, ElementType, ElementSetType, ContextType> node,
                 const ContextType& context,
                 const ElementSetType& used,
                 bool bNewElement);
    
    void addElements(ElementSetType elements);
    size_t queueSize();
    void removeElements(const ElementSetType& elements, bool bRecurse = false);
    
    double score(const ContextType& context, const ElementSetType& used) {
        return this->edge.cachedScore(context, used);
    }
};


//### The Queue Template
template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
class CBranchedQueue {
public:
    friend struct BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>;

public:
    const ContextType* pContext;
    const ElementSetType* pUsedElements;

protected:
    BranchedQueueNodeList_t<EdgeType, ElementType, ElementSetType, ContextType> data;
    size_t nEdges;
    size_t nElements;
    bool validNElementCache;

public:
    CBranchedQueue(const ContextType* pCtx, const ElementSetType* pSet)
        : pContext(pCtx), pUsedElements(pSet), data(), nEdges(0), nElements(0), validNElementCache(false) {}
    
    ~CBranchedQueue() = default;

    bool empty() const { return this->data.empty(); }
    size_t size() const { return this->nEdges; }
    
    size_t queueSize() {
        if (validNElementCache) {
            return this->nElements;
        }
        nElements = this->nEdges;
        for (auto& node : this->data) {
            nElements += node->queueSize();
        }
        validNElementCache = true;
        return this->nElements;
    }

    const EdgeType& top() const {
        if (this->data.empty()) {
            throw std::logic_error("Attempt to call top on empty CBranchedQueue");
        }
        return this->data.front()->edge;
    }

    void addEdge(const EdgeType& edge) {
        auto node = std::make_unique<BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>>(edge);
        this->addNode(std::move(node), true);
    }

    void cannabalize() { this->removeTop(true); }
    void pop() { this->removeTop(false); }

protected:
    void addNode(BranchedQueueNode_pt<EdgeType, ElementType, ElementSetType, ContextType> node, bool bNewElement) {
        if (bNewElement) {
            this->validNElementCache = false;
        }
        const ContextType& context = *(this->pContext);
        const ElementSetType& usedElements = *(this->pUsedElements);

        if (this->data.empty()) {
            data.push_front(std::move(node));
            this->nEdges++;
            return;
        }

        auto insIt = this->data.before_begin();
        auto mergeIt = this->data.end();
        auto preMergeIt = this->data.before_begin();

        for (auto it = this->data.begin(), pit = this->data.before_begin();
             it != this->data.end() && mergeIt == this->data.end();
             it++, pit++) 
        {
            const auto& curNode = *it;
            if (curNode->score(context, usedElements) > node->score(context, usedElements)) {
                insIt = it;
            }

            // Abstracted matching verification logic for elements/mates
            for (const ElementType& elem : node->edge.readSet) {
                if (curNode->descendentElements.count(elem) ||
                    (elem->mate && curNode->descendentElements.count(elem->mate))) 
                {
                    preMergeIt = pit;
                    mergeIt = it;
                    break;
                }
            }
        }

        if (mergeIt == this->data.end()) {
            this->data.insert_after(insIt, std::move(node));
            this->nEdges++;
            return;
        }

        auto& mergeNode = *mergeIt;
        if (mergeNode->score(context, usedElements) >= node->score(context, usedElements)) {
            mergeNode->descendentElements.insert(node->descendentElements.begin(), node->descendentElements.end());
            node->removeElements(mergeNode->edge.readSet, false);
            mergeNode->addNode(std::move(node), context, usedElements, bNewElement);
            return;
        }

        node->descendentElements.insert(mergeNode->descendentElements.begin(), mergeNode->descendentElements.end());
        mergeNode->removeElements(node->edge.readSet, true);
        
        node->addNode(std::move(mergeNode), context, usedElements, bNewElement);
        this->data.erase_after(preMergeIt);
        this->data.insert_after(insIt, std::move(node));
    }

    void removeElements(const ElementSetType& set) {
        for (auto& node : this->data) {
            node->removeElements(set, true);
        }
    }

    void removeTop(bool cannabalize = false) {
        if (this->data.empty()) {
            throw std::logic_error("Attempt to remove top element on empty CBranchedQueue");
        }
        auto node = std::move(this->data.front());
        this->data.pop_front();
        this->nEdges--;
        this->nElements--;

        if (node->childQueue) {
            auto& childVec = node->childQueue->data;
            for (auto it = childVec.begin(); it != childVec.end(); it++) {
                if (cannabalize) {
                    (*it)->addElements(node->edge.readSet);
                }
                this->addNode(std::move(*it), false);
            }
        }
    }
};

// Implementations of BranchedQueueNode_t methods
template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
void BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>::addNode(
    BranchedQueueNode_pt<EdgeType, ElementType, ElementSetType, ContextType> node,
    const ContextType& context,
    const ElementSetType& used,
    bool bNewElement) 
{
    if (!node->edge.readSet.size()) {
        if (node->childQueue) {
            for (auto& cNode : node->childQueue->data) {
                this->addNode(std::move(cNode), context, used, false);
            }
        }
        return;
    }
    if (!this->childQueue) {
        this->childQueue = std::make_unique<CBranchedQueue<EdgeType, ElementType, ElementSetType, ContextType>>(&context, &used);
    }
    this->childQueue->addNode(std::move(node), bNewElement);
}

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
void BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>::addElements(ElementSetType elements) {
    for (auto it = elements.begin(); it != elements.end();) {
        const ElementType& elem = *it;
        if (!this->descendentElements.count(elem)) {
            it = elements.erase(it);
        } else if (this->originalElements.count(elem)) {
            this->edge.addRead(elem); // Assumes Edge still implements addRead or general insert mapping
            if (elem->mate && this->originalElements.count(elem->mate)) {
                this->edge.addRead(elem->mate);
            }
            it = elements.erase(it);
        } else if (elem->mate && this->originalElements.count(elem->mate)) {
            this->edge.addRead(elem->mate);
            it = elements.erase(it);
        } else {
            it++;
        }
    }
    if (this->childQueue) {
        for (auto& cNode : this->childQueue->data) {
            cNode->addElements(elements);
        }
    }
}

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
size_t BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>::queueSize() {
    if (this->childQueue) return this->childQueue->queueSize();
    return 0;
}

template <typename EdgeType, typename ElementType, typename ElementSetType, typename ContextType>
void BranchedQueueNode_t<EdgeType, ElementType, ElementSetType, ContextType>::removeElements(const ElementSetType& elements, bool bRecurse) {
    for (const ElementType& elem : elements) {
        this->edge.removeRead(elem);
        if (elem->mate) {
            this->edge.removeRead(elem->mate);
        }
    }
    if (bRecurse && this->childQueue) {
        this->childQueue->removeElements(elements);
    }
}
#endif //SURVEYOR_BRANCHED_QUEUE_H


